PR for a wonderful readme.md
nearlySplat/Gap_Utilities pull request #62
Opened 2021-01-18 13:25 UTC by FrostyTheDumDum

Added a Readme.MD cause why the fuck not lol

2021-01-18 13:32 UTC, nearlySplat requested changes
I also feel like the image is a bit bland.

2021-01-18 13:32 UTC, nearlySplat commented on README.md
> +https://discordapp.com/oauth2/authorize?client_id=791700965081612288&scope=bot&permissions=8 ~~gimme admin lol~~
I think the README should be about the code, how to contribute and not the Ad. Sorry :(

2021-01-18 14:05 UTC, FrostyTheDumDum commented on README.md
> +https://discordapp.com/oauth2/authorize?client_id=791700965081612288&scope=bot&permissions=8 ~~gimme admin lol~~
Lol what???????????????????????????????????????????????????? :(

2021-01-20 18:51 UTC, closed without merging

2021-01-30 20:53 UTC, nearlySplat commented
@FrostyTheDumDum should you ever feel like re-opening this, do, but for now, I will keep it closed. I don't think a README is something really needed at the moment.